### ISSUE TITLE
Move repo to GitHub organization

### ISSUE THREAD

**Issue by goronfreeman** [joshcampbell191/openfpga-cores-inventory#12]
A [Reddit comment](https://www.reddit.com/r/AnaloguePocket/comments/xmeo3m/comment/ipz8t08/?utm_source=share&utm_medium=web2x&context=3) suggested that we create a GitHub organization and move the repo there. This would give us a better URL to serve up the JSON at `https://openfpga-cores-inventory.github.io/`.

**Comment by mattpannella** [comment]
just to bump this, i think this would be a good place to stick the repo mirroring jotego's cores (or, i guess, any other mirrors we may need). I have it on my personal account right now

**Comment by joshcampbell191** [comment]
I’ll put some time aside to look at things this week. Perhaps we can collaborate on a few items.

**Comment by joshcampbell191** [comment]
I'm just about ready to move everything over. 

I created the following organization to host everything: https://github.com/openfpga-cores-inventory

You'll notice that I split the analogue pocket cores from the website to try and keep things organized.

**Comment by joshcampbell191** [comment]
@mattpannella @neil-morrison44 The site has been moved to new repository. All that's left is to setup a "redirect" for users who frequent the page. Keep in mind that this redirect will be handled mostly through the `meta` tag using `jekyll-redirect-from` and won't work for API requests.

Here's a link to the new site: https://openfpga-cores-inventory.github.io/ 

Note that the API endpoint has changed to: https://openfpga-cores-inventory.github.io/analogue-pocket/api/v1/cores.json

**Comment by neil-morrison44** [comment]
👍🏻 I’ll push out a version of Pocket Sync tonight pointing to the new one - how long will the old one stay up? (Ideally it’s long enough to not have the app / cli crash, even if it doesn’t get pushed any updates)

**Comment by joshcampbell191** [comment]
Both sites will remain online. I will be keeping this repository up for historical purposes but will lock it down after the redirect is in place and add a notice for users. Once that's done, I'll be disabling the actions that keep everything up to date.

**Comment by joshcampbell191** [comment]
Final update: The redirects are now in place. I've decided to keep both sites running for the next month or so to give people the chance to catch up / enjoy the holidays after which I'll be marking this repository as archived.

**Comment by joshcampbell191** [comment]
Now that everyone has had the chance to migrate, I'll mark the repository as archived.
