### ISSUE TITLE
Add the ability to developers to exclude a core from the API

### ISSUE THREAD

**Issue by goronfreeman** [joshcampbell191/openfpga-cores-inventory#18]
On a couple occasions, @ericlewis has [requested](https://github.com/mattpannella/pocket_core_autoupdate_net/pull/25) for @mattpannella's updater not pull in one of his cores. We should allow developers a way to signal to the API not to serve up a certain repository if they don't feel the core is ready for the limelight. One way to do this would be to check for a certain semver label on the Git tag. For example `0.1.0-noupdate`, or something like that.

**Comment by joshcampbell191** [comment]
I noticed the same thing when reviewing comments in the auto updater repository. The approach you proposed sounds good to me. Let's wait and see if we can get more feedback before implementing this.

**Comment by agg23** [comment]
As discussed on Discord, this should just use the `prerelease` flag already built into Discord. Updaters can then have a setting to allow users to download prerelease cores.

**Comment by goronfreeman** [comment]
Closed by mattpannella/pocket_core_autoupdate_net#32
