### ISSUE TITLE
Include a donation link for the developer of each core in the api

### ISSUE THREAD

**Issue by mattpannella** [joshcampbell191/openfpga-cores-inventory#19]
This way the updaters can quickly/simply throw up a link to help get support for developers

**Comment by joshcampbell191** [comment]
Hey @mattpannella! Thanks for bringing forward this idea. After some investigation, I've come up with a solution that should satisfy the request. 

Here's what I'd like to propose:

For each of the `repositories` in the [`repos.yml`](https://github.com/joshcampbell191/openfpga-cores-inventory/blob/master/_data/repos.yml), we could check for the presence of a [`.github/FUNDING.yml`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository#about-funding-files) file. This can be done via the [repository contents API](https://docs.github.com/en/rest/repos/contents#about-the-repository-contents-api). If the file exists, then its contents will be used to populate a new `sponsor` section that can be added to the JSON output.

```json
{
  "identifier": "my.identifier",
  ...
  "sponsor": {
    "community_bridge": "https://community_bridge.url",
    "github": [ "https://github.url" ],
    "issuehunt": "https://issuehunt.url",
    "ko_fi": "https://ko_fi.url",
    "liberapay": "https://liberapay.url",
    "open_collective": "https://open_collective.url",
    "otechie": "https://otechie.url",
    "patreon": "https://patreon.url",
    "tidelift": "https://tidelift.url",
    "custom": [ "https://custom.url" ]
  }
  ...
}
```

If the file doesn't exist, we can check if the user has created a [`default community health file`](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file) for [`FUNDING.yml`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository#about-funding-files) file. If the `default community health file` for `FUNDING.yml` is found, its contents will be used as the defaults for repositories that don't specify their own `FUNDING.yml`. This behavior is in-line with how `default community health files` work.

Let me know if this works for you and we can start working on this request as time permits.

**Comment by mattpannella** [comment]
that's a really great idea actually. 
not even sure how I'd surface the info in a cli app, maybe show a random sponsor link each run or something. but once it's there people can figure out what to do with it

**Comment by neil-morrison44** [comment]
I was just about to request this then I noticed it's here already!

<img width="912" alt="Screenshot 2022-11-13 at 15 46 19" src="https://user-images.githubusercontent.com/2095051/201530693-02df5295-f545-403d-85f1-32f0ae0fd3ec.png">

Was hoping to funnel people towards the sponsorships / patreons / etc when they click into the "info" view of a core (screenshot just shows the list since that's as far as the implementation's got so far)

**Comment by joshcampbell191** [comment]
I started working on it this morning and am just about done. I should be able to have it available shortly.

**Comment by joshcampbell191** [comment]
The PR is up. Once it's been reviewed by @goronfreeman, the new `sponsor` section should be available in the API.

**Comment by joshcampbell191** [comment]
After not hearing back, I've opted to merge the PR so you guys can keep moving forward.
