### ISSUE TITLE
snow bros 2 is out. 

### ISSUE THREAD

**Issue by gregmariotti** [joshcampbell191/openfpga-cores-inventory#25]
arcade game. 

https://github.com/psomashekar/pram0d-pocket-dist-public

**Comment by goronfreeman** [comment]
The repository doesn't use the release feature of GitHub, which both this application and the consumers of its API use. Unfortunately that means we don't have a good way to add this without creating a hack specifically for this repository. This isn't something we're looking to do any time soon, but pull requests are welcome.

**Comment by goronfreeman** [comment]
Alternatively, pram0d said that someone could fork the repository and add releases themselves, but that would require monitoring any updates he makes and updating the release zips manually. If someone takes on that work, then we could get it added.

**Comment by goronfreeman** [comment]
I added Snow Bros. 2 to the website, and we're working on getting this added to the API in #26. Going to close this issue and track work in the other one.
