### ISSUE TITLE
JT cores missing

### ISSUE THREAD

**Issue by Xukkorz** [joshcampbell191/openfpga-cores-inventory#27]
Ordered as below
1. Name
2. Platform
3. Author
4. Version
5. Date

Ghosts'n Goblins
1. jtgng
2. Ghosts'n Goblins
3. Jotego
4. no version
5. October 4th, 2022

Pang!
1. jtpang
2. Pang!
3. Jotego
4. no version
5. October 14th, 2022

Both cores listed as early access with public access information still to come. Cores are both on Jotego's Patreon

**Comment by goronfreeman** [comment]
Thanks! Those are added now. If JT adds more cores to his Patreon, please open up another issue with the same information, since we'll have to update these manually while they're behind the paywall.
