### ISSUE TITLE
pram0d's new cores are available

### ISSUE THREAD

**Issue by DrAvedi** [joshcampbell191/openfpga-cores-inventory#28]
3 new cores are now listed at https://github.com/psomashekar/pram0d-pocket-dist-public

**Comment by goronfreeman** [comment]
Got those added to the table. Still need to do some additional work to add them to the API, but that's coming.

**Comment by DrAvedi** [comment]
Thanks! pram0d is making things harder by burying these in a repository instead of making official releases for his cores, so thanks for going the extra mile to add them to the API.
