### ISSUE TITLE
Include not-required assets from data.json

### ISSUE THREAD

**Issue by mattpannella** [joshcampbell191/openfpga-cores-inventory#39]
I think it would be useful to include all of the assets in the data.json file for each core, instead of just the ones flagged as required. instead just include that required flag in the api response, for updaters to handle however they want.
this came up because the super gameboy core has both bios files in data.json not listed as required, but..they kind of are. 
```json
      {
        "name": "SGB BIOS SNES",
        "id": "0x103",
        "required": false,
        "filename": "sgb_snes.smc",
        "parameters": "0x2",
        "extensions": [
          "smc"
        ],
        "size_exact": null,
       "size_maximum": 522488,
        "address": "0x00000000"
      },
      {
        "name": "SGB BIOS GB",
        "id": "0x104",
        "required": false,
        "filename": "sgb_boot.bin",
        "parameters": "0x2",
        "extensions": [
          "bin"
        ],
        "size_exact": 256,
        "address": "0x60000f00"
      }
```

**Comment by mattpannella** [comment]
looking through a bunch of the new spiritualized cores, the majority of the necessary bios files are all marked with required: false. so i definitely think including them makes sense, otherwise updaters are just going to have to manually maintain a secondary list of required files, which kind of cancels out most of the point of including these in the api

the only thing is it's going to add a bunch of extra unnecessary data to the api response like every core supporting .sav files, and some other random stuff. but i guess thats not a huge deal? not sure if anyone else has a strong opinion on it

**Comment by joshcampbell191** [comment]
If this is still required, feel free to open another issue here https://github.com/openfpga-cores-inventory/analogue-pocket
