### ISSUE TITLE
Include the core's self reported version number (from `core.json` -> `core.metadata.version`) somewhere

### ISSUE THREAD

**Issue by neil-morrison44** [joshcampbell191/openfpga-cores-inventory#41]
<img width="281" alt="Screenshot 2022-11-28 at 21 24 08" src="https://user-images.githubusercontent.com/2095051/204383943-7611be0d-8383-4049-9c8a-27fb50f36b62.png">

- in Pocket Sync I'm doing some nasty heuristic stuff to check `( release | prerelease ).tag_name` vs what the core self-reports in its `core.json` file which is fine for _most_ cores...
- Except
  - NeoGeo & PDP-1 don't have tags that match their version (NeoGeo's close & I could probably get it by widening up my heuristic)
  - GameGear misreports it's internal version number so always looks like it has an update (this is something Spiritualized will need to fix, [there's a github issue for it](https://github.com/spiritualized1997/openFPGA-GG/issues/6))
  - Any non-github-releases cores might not fit well with the `tag_name` paradigm

Ideally there's a root level `version` param just re-reporting whatever the core says in it's core.json file

---

Also, let me know if there's any funding links etc you guys have got & I'll get them into the launch page of Pocket Sync beside the Thank You since it's this project that'll be keeping it up to date

**Comment by joshcampbell191** [comment]
Sorry I haven't been able to get around to this project in a little bit due to a busy schedule. I'll see about adding this feature shortly.

**Comment by joshcampbell191** [comment]
The core version has been added to the v0 / v1 API.

**Comment by joshcampbell191** [comment]
I'm not looking for any funding on this project. I enjoy working on it when time permits and appreciate the effort the community is putting in.

**Comment by neil-morrison44** [comment]
👍🏻 works great, thanks
