### ISSUE TITLE
`Mazamars312.amiga` casing

### ISSUE THREAD

**Issue by neil-morrison44** [joshcampbell191/openfpga-cores-inventory#44]
Hey, 

looks like this is `Mazamars312.Amiga` once it's installed

<img width="235" alt="Screenshot 2022-12-08 at 18 48 08" src="https://user-images.githubusercontent.com/2095051/206541327-3b3a6462-d12d-47eb-9965-0a2f32cfdfe7.png">

The platform name is a lowercase `amiga` on the Pocket, which confuses things, but the platform for `NeoGeo` is `ng` on the Pocket and it has a `"identifier": "Mazamars312.NeoGeo",`

(had a look at doing a PR but I'm only seeing it specified in the auto-generated file so I'm not sure where it's coming from)

**Comment by neil-morrison44** [comment]
Up to you lot if you want to change this - @mattpannella pointed out that the `shortname` is `"amiga"` so that's where it's coming from.

Don't think there's anything in the docs which says that the shortname has to match the bit after the dot - we've just been lucky so far

> shortname: string
> Short name used for filesystem. > Maximum length 31 characters.

I can probably just have that bit of Pocket Sync be case insensitive (and I might have to anyway for the screenshot processing it does)

**Comment by joshcampbell191** [comment]
The identifier is currently built by combining the author and shortname from the [`cores.json`](https://github.com/Mazamars312/Analogue-Amiga/blob/Mazamars312.Amiga.500.0.0.5-Alpha/dist/Cores/Mazamars312.Amiga/core.json) file. We could use the folder in the Cores directory instead which should result in more accurate results.

**Comment by neil-morrison44** [comment]
Up to you, it could be awkward trying to find the folder name for the GB / GBC cores since those are packaged together.

I read a little farther down in the docs and found this:

> The core folder name should follow this convention: AuthorName.CoreName where AuthorName and CoreName correspond to author and shortname in core.json respectively.

I’ll open an issue on the Amiga core since they don’t match

**Comment by neil-morrison44** [comment]
Raised this https://github.com/Mazamars312/Analogue-Amiga/issues/11

The inventory’s doing the right thing by Analogue’s docs so I’ll close this out
