### ISSUE TITLE
Feature Request: some sort of "news" section in the JSON response (or via another API)

### ISSUE THREAD

**Issue by neil-morrison44** [joshcampbell191/openfpga-cores-inventory#45]
This'll be quite a vague feature request since I don't have an exact use for it, but adding an (autogenerated) section like:

```json
{
  "news": [
    { 
      "title": "agg23's SNES core updated to 0.4.2",
      "core_identifier": "agg23.snes",
      "news_type": "update",
      "date": "2022-12-11T01:28:02Z"
    },
   {
     "title": "New jtgng core from JOTEGO",
     "core_identifier": "jotego.jtgng",
     "news_type": "new_core",
     "date": "2022-12-9T01:28:02Z"
   }
  ]
}
``` 

In Pocket Sync I'd check for news stories since the last time the user used the app & present them, & now @mattpannella's CLI updater has a splash screen the same could happen there.

Could also be supplementary to the JSON, would make sense as an RSS feed (if those were a thing anymore).

Eventually, if I add (optional) notifications to Pocket Sync I could use it to pop up notifications for new cores / updates etc

**Comment by joshcampbell191** [comment]
That's a great idea! I've been a little busy re-working things since I've begone moving things to a new site / repository. Once this is done, I'll give you a heads up. Personally, I was leaning towards an RSS feed since the functionality is built into the Jekyll templates.

**Comment by joshcampbell191** [comment]
Now that v2 is out of the way, I've gone ahead and implemented this.

The Atom feed can be found here: https://openfpga-cores-inventory.github.io/analogue-pocket/feed.xml

Note that it pulls the contents from the info.txt to populate the contents field of the Atom entry. Also, the feed is limited to the latest 10 updates.
